### PR TITLE
Make VectorIndex extend VectorData

### LINKED ISSUE #32: Make `VectorIndex` inherit from `VectorData` instead of `Index`
See https://github.com/NeurodataWithoutBorders/nwb-schema/pull/448

### PR DESCRIPTION
**Pull request by rly**
## Summary of changes

- Resolve #32

## PR Checklist
- [x] Add release notes for the PR to `docs/source/format_release_notes.rst`

### CODE REVIEW

**Comment by oruebel** [comment]
If the ``Index`` type is unused, then we may want to remove it. I don't think anyone is using it so it should be save to remove. Is that correct @ajtritt

**Comment by ajtritt** [comment]
> If the Index type is unused, then we may want to remove it. 

Agreed. It's not used anywhere else.

**Comment by rly** [comment]
Fixed. I also removed:
https://github.com/hdmf-dev/hdmf-common-schema/blob/9b159ef7d0989f7c92229b2a6c4c02c93ecee69b/common/table.yaml#L151-L153

which is now redundant.

**Comment by oruebel** [comment]
> Fixed. I also removed:

I think it would be useful then to update the doc for DynamicTable to describe that VectorData may be indexed  by VectroIndex to create ragged array columns and that the name of the VectorIndex is expected to be the same as the VectorData followed by the ``_index``. The main reason is, that when removing VectorIndex as an explicit include the ability create ragged columns becomes a bit of "hidden" feature in the schema (even though formally nothing changes).

**Comment by rly** [comment]
I updated the docstrings for `DynamicTable` and `VectorIndex`. Please re-review

**Comment by ajtritt** [comment]
Looks good to me. Good luck with the API changes....

**Pull request merged**
