### PR TITLE
HERD name change

### PR DESCRIPTION
**Pull request by mavaylon1**
## Summary of changes
Updates ExternalResources to have a uniform name throughout the codebase and the literature, which is now "HERD".

## PR checklist for schema changes

- [x] Update the version string in `docs/source/conf.py` and `common/namespace.yaml` to the next version with the suffix "-alpha"
- [x] Add a new section in the release notes for the new version with the date "Upcoming"
- [x] Add release notes for the PR to `docs/source/hdmf_common_release_notes.rst` and/or
  `docs/source/hdmf_experimental_release_notes.rst`

### CODE REVIEW

**Comment by mavaylon1** [comment]
Note:
Merge after TermSet updates are merged

**Comment by rly** [comment]
Can you spell out what HERD stands for in the docstrings and release notes?

**Comment by mavaylon1** [comment]
> Can you spell out what HERD stands for in the docstrings and release notes?

Good call. I added it here and also to the class in HDMF

**Review by rly — APPROVED** [review]

**Review by oruebel — APPROVED** [review]

**Comment by rly** [comment]
Thanks. Looks good to me!

**Pull request merged**
