### PR TITLE
Prepare 1.5.1 release

### PR DESCRIPTION
**Pull request by rly**
## Summary of changes

- Add @mavaylon1 to experimental namespace and credits
- Adjust indentation for `resources.yaml`
- Split release notes by namespace
- Update copyright date
- Update version of hdmf-common to 1.5.1. 
  - There are no changes to this namespace but there are changes to the hdmf-experimental namespace (0.1.0 -> 0.2.0). I increased the version of the hdmf-common namespace because in order to make a public release/tag of the repo, the version of the repo/schema must be increased, and the version of the repo/schema is currently linked to the version of the hdmf-common namespace. An alternative approach would be to use a independent versioning scheme for the repo/schema, such as `1.5.1+1.5.0-0.2.0` or resetting the version `2.0.0`, but I think this would be too confusing. 

## PR checklist for schema changes

- [x] Update the version string in `docs/source/conf.py` and `common/namespace.yaml` to the next version with the suffix "-alpha"
- [x] Add a new section in the release notes for the new version with the date "Upcoming"
- [x] Add release notes for the PR to `docs/source/format_release_notes.rst`

### CODE REVIEW

**Comment by rly** [comment]
This release is necessary before releasing the latest HDMF which uses the experimental features in hdmf-experimental 0.2.0

**Comment by bendichter** [comment]
we should test this out in MatNWB prior to release. @ln-vidrio, can you take a look?

**Comment by ln-vidrio** [comment]
@bendichter This looks good and builds without error.

**Comment by bendichter** [comment]
Great! Looks good to me then

**Review by bendichter — APPROVED** [review]

**Pull request merged**
